config/routes.rb
Practice::Application.routes.draw do
  resources :passions do
    resources :sessions
  end

  get "home/index"
  
  root :to => "passions#index"

end

app/models/passion.rb
class Passion < ActiveRecord::Base
  
  validates :name, :presence => true
  
  has_many :sessions, :dependent => :destroy
  

  
  
  
  
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :passion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/passions_controller.rb
class PassionsController < ApplicationController
  USER, PASSWORD = 'graeme', 'secret'

  before_filter :authentication_check, :except => [:index, :show]



    
    
  # GET /passions
  # GET /passions.json
  def index
    @passions = Passion.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passions }
    end
  end

  # GET /passions/1
  # GET /passions/1.json
  def show
    @passion = Passion.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @passion }
    end
  end

  # GET /passions/new
  # GET /passions/new.json
  def new
    @passion = Passion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @passion }
    end
  end

  # GET /passions/1/edit
  def edit
    @passion = Passion.find(params[:id])
  end

  # POST /passions
  # POST /passions.json
  def create
    @passion = Passion.new(params[:passion])

    respond_to do |format|
      if @passion.save
        format.html { redirect_to @passion, notice: 'Passion was successfully created.' }
        format.json { render json: @passion, status: :created, location: @passion }
      else
        format.html { render action: "new" }
        format.json { render json: @passion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passions/1
  # PUT /passions/1.json
  def update
    @passion = Passion.find(params[:id])

    respond_to do |format|
      if @passion.update_attributes(params[:passion])
        format.html { redirect_to @passion, notice: 'Passion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @passion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passions/1
  # DELETE /passions/1.json
  def destroy
    @passion = Passion.find(params[:id])
    @passion.destroy

    respond_to do |format|
      format.html { redirect_to passions_url }
      format.json { head :ok }
    end
  end

  private

  def authentication_check
    authenticate_or_request_with_http_basic do |user, password|
      user == USER && password == PASSWORD
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  USER, PASSWORD = 'graeme', 'secret'
  
  before_filter :authentication_check, :except => [:index, :show]
  
  def create
    @passion = Passion.find(params[:passion_id])
    @session = @passion.sessions.create(params[:session])
    redirect_to passion_path(@passion)
  end
  
  def destroy
    @passion = Passion.find(params[:passion_id])
    @session = @passion.sessions.find(params[:id])
    @session.destroy
    redirect_to passion_path(@passion)
  end
  
  private

  def authentication_check
    authenticate_or_request_with_http_basic do |user, password|
      user == USER && password == PASSWORD
    end
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passions_helper.rb
module PassionsHelper
  
  def get_time passion
    @practice_time = 0
    @sessions = passion.sessions.all
      
    @sessions.each do |session|
      @practice_time += session.time.to_i
    end
    @practice_time
  end
    
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
Please!!!

<%= link_to "Passions", passions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practiced</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="page-wrapper">
<div class="top-bar"><%= link_to image_tag("logo.png"), passions_path %></div>
<%= yield %>
</div>
</body>
</html>

app/views/passions/_form.html.erb
<%= form_for(@passion) do |f| %>
  <% if @passion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passion.errors.count, "error") %> prohibited this passion from being saved:</h2>

      <ul>
      <% @passion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passions/edit.html.erb
<h1>Editing passion</h1>

<%= render 'form' %>

<%= link_to 'Show', @passion %> |
<%= link_to 'Back', passions_path %>

app/views/passions/index.html.erb
<h1>Stuff that you love</h1>

<% @passions.each do |passion| %>

<div class="box">
<div class="time_box">
<div class="time">
<h1><%= get_time passion %></h1>
<h2>hours</h2>
</div>
</div>

<div class="display_box">
<h1><%= link_to passion.name, passion %></h1>
<p><%= passion.description %></p>
<%= link_to 'Add a Practice Session', passion %> - 
<%= link_to 'Edit', edit_passion_path(passion) %> - 
<%= link_to 'x', passion, :confirm => 'Are you sure?', :method => :delete %>
</div>
</div>
<% end %>


<div class="clear"></div>

<%= link_to 'New Passion', new_passion_path %>

app/views/passions/new.html.erb
<h1>New passion</h1>

<%= render 'form' %>

<%= link_to 'Back', passions_path %>

app/views/passions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
<div class="time_box">
<div class="time">
<h1><%= get_time @passion %></h1>
<h2>hours</h2>
</div>
</div>

<div class="display_box">
<h1>
  <%= @passion.name %>
</h1>

<p>
  <%= @passion.description %>
</p>
</div>
</div>
<div class="clear"></div>


<h2>Previous sessions</h2>

<%= render @passion.sessions %>


<div class="clear"></div>
<br />
<h2>Add a session:</h2>

<%= render "sessions/form" %>


<%# link_to 'Edit', edit_passion_path(@passion) %>

<%= link_to 'Back to Passions', passions_path %>